service: hstdeploy

frameworkVersion: '3'


provider:
  name: aws

  runtime: python3.8
  stage: dev
  region: ${file(./config.${self:provider.stage}.yml):REGION}
  environment:
    db_host: ${file(./config.${self:provider.stage}.yml):DBHOST}
    db_name:  ${file(./config.${self:provider.stage}.yml):DBNAME}
    db_pass:  ${file(./config.${self:provider.stage}.yml):DBPASS}
    db_port:  ${file(./config.${self:provider.stage}.yml):DBPORT}
    db_user:  ${file(./config.${self:provider.stage}.yml):DBUSER}

package:
  patterns:
    - '!src/**/test_*.py'
    - '!src/**/__pycache__'
    - '!config.*.yml'

functions:
  main:
    timeout: 900
    memorySize: 1024
    ### uncomment handler to deploy locally ...serverless can't handle deploying ecr docker image locally
    handler: handler.deploy
    #image: 448319106780.dkr.ecr.eu-west-3.amazonaws.com/eneos-ecr:latest
    #image : 448319106780.dkr.ecr.eu-west-3.amazonaws.com/eneos-ecr@sha256:292d1d5f6dfb6d707fa417caf7a56c0fb95e5e358e22d56e66e1bd39cefee8b3
